var examples =

[{
    "value":"0",
    "children":[
       {
          "value":"1",
          "children":[
             {
                "value":"2",
                "children":[
                   {
                      "value":"4",
                      "children":[
                         {
                            "value":"99"
                         },
                         {
                            "value":"96"
                         }
                      ]
                   },
                   {
                      "value":"10",
                      "children":[
                         {
                            "value":"105"
                         },
                         {
                            "value":"104"
                         }
                      ]
                   }
                ]
             },
             {
                "value":"77",
                "children":[
                   {
                      "value":"4",
                      "children":[
                         {
                            "value":"99"
                         },
                         {
                            "value":"96"
                         }
                      ]
                   },
                   {
                      "value":"10",
                      "children":[
                         {
                            "value":"105"
                         },
                         {
                            "value":"104"
                         }
                      ]
                   }
                ]
             }
          ]
       },
       {
          "value":"3",
          "children":[
             {
                "value":"9",
                "children":[
                   {
                      "value":"27",
                      "children":[
                         {
                            "value":"99"
                         },
                         {
                            "value":"96"
                         }
                      ]
                   },
                   {
                      "value":"10",
                      "children":[
                         {
                            "value":"105"
                         },
                         {
                            "value":"104"
                         }
                      ]
                   }
                ]
             },
             {
                "value":"77",
                "children":[
                   {
                      "value":"4",
                      "children":[
                         {
                            "value":"99"
                         },
                         {
                            "value":"96"
                         }
                      ]
                   },
                   {
                      "value":"10",
                      "children":[
                         {
                            "value":"105"
                         },
                         {
                            "value":"104"
                         }
                      ]
                   }
                ]
             }
          ]
       }
    ]
 },
 {
    "value":"-",
    "children":[
       {
          "value":"+",
          "children":[
             {
                "value":"2"
             },
             {
                "value":"x"
             }
          ]
       },
       {
          "value":"*",
          "children":[
             {
                "value":"y"
             },
             {
                "value":"3"
             }
          ]
       }
    ]
 },
 {
    "value":"100",
    "children":[
       {
          "value":"48 (a)"
       },
       {
          "value":"52",
          "children":[
             {
                "value":"22",
                "children":[
                   {
                      "value":"10 (?)"
                   },
                   {
                      "value":"12 (g)"
                   }
                ]
             },
             {
                "value":"30",
                "children":[
                   {
                      "value":"13",
                      "children":[
                         {
                            "value":"4 (k)"
                         },
                         {
                            "value":"9 (c)"
                         }
                      ]
                   },
                   {
                      "value":"17 (p)"
                   }
                ]
             }
          ]
       }
    ]
 }];